### ISSUE TITLE
Antragstellung

### ISSUE THREAD

**Issue by mojoaxel** [freifunk/AdvisoryCouncil#2]
Genau beschreiben, wie Anträge an den AC herangetragen werden können, in welcher Form und in welchem Zeitraum eine Antwort erfolgen soll/muss.

**Comment by mathiashro** [comment]
Bisher hat sich in der Beratung keine besondere Form ergeben, daher weiterhin offen (per Mail) lt. Arbeitsrichtlinien. Aus meiner Sicht damit ausreichend genau beschrieben. Gern wieder öffnen, falls noch etwas zu bearbeiten.
