### ISSUE TITLE
Zuständigkeit

### ISSUE THREAD

**Issue by mojoaxel** [freifunk/AdvisoryCouncil#3]
Es sollte beschrieben werden für welche Form von Fragestellungen der sich der AC zuständig sieht. In welcher Form werden Ratschläge, Stellungnahmen oder Beschlüsse weitergegeben und wann werden Anträge abgelehnt.

**Comment by mathiashro** [comment]
Aus meiner Sicht inzwischen ausreichend genau beschrieben. Gern wieder öffnen, falls noch etwas zu bearbeiten.
